services:
  # Nombre del servicio: db | Nombre del contenedor: dev-n8n-db
  db:
    container_name: ${INSTANCE_PREFIX}-n8n-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-n8n_db}
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - internal_net

  proxy:
    container_name: ${INSTANCE_PREFIX}-n8n-proxy
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./volumes/npm_data:/data
      - ./volumes/npm_letsencrypt:/etc/letsencrypt
    networks:
      - internal_net
      - external_net

  tunnel:
    container_name: ${INSTANCE_PREFIX}-n8n-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run --token ${CLOUDFLARE_TOKEN}
    depends_on:
      - proxy
    networks:
      - internal_net

  n8n:
    container_name: ${INSTANCE_PREFIX}-n8n-app
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - N8N_HOST=${N8N_ASISTENTE_URL}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_ASISTENTE_URL}/
      - N8N_ENCRYPTION_KEY=${N8N_KEY_ASISTENTE}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n_db}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-admin}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/n8n_asistente_data:/home/node/.n8n
    depends_on:
      - db
    networks:
      - internal_net
      - external_net

networks:
  internal_net:
    name: ${INSTANCE_PREFIX}_n8n_internal
    driver: bridge
  external_net:
    name: ${INSTANCE_PREFIX}_n8n_external
    driver: bridge